### ISSUE TITLE
Support for injecting css into a proxied html

### ISSUE THREAD

**Issue by bartosz-wesolowski-wttech** [rustybox/webpack-dev-server-inject-scripts#2]
Hello,

I recently found this plugin and it works great in my setup -> CMS appliation creates a markup for a page and with this plugin custom js is added to the page on the fly while developing :) 

I wonder whether there is an option to provide same functionality like `injectStyles` to also add custom CSS on the fly to the proxied pages. 

Cheers

**Comment by p-m-j** [comment]
Hey there, glad it’s working for you!

So styles (css/sass) in a dev scenario would be imported by your javascript, that way the style sheets can make use of hot module reloading.

In a production build you would be switching to MiniCssExtractPlugin to create your css bundles and HtmlWebpackPlugin to reference the css and js bundles.

**Comment by bartosz-wesolowski-wttech** [comment]
I am not sure I understand `So styles (css/sass) in a dev scenario would be imported by your javascript, that way the style sheets can make use of hot module reloading.` part. I am a fresh new member of webpack/front-end development world, sorry :) 

Currently to work in dev mode we need to get the file from the CMS (copy markup), save it in static index.html and then use this file in devServer with `HtmlWebpackPlugin` (config below). In dev server our js and css bundle is dynamically added to the markup so every change triggers reload and updates are visible right away. 
```
plugins: [
            new HtmlWebpackPlugin({
                template: path.resolve(__dirname, SOURCE_ROOT + '/static/index.html')
            })
]
```

I would like to achieve similar behavior but without a need to create static index.html file and without need for copy-pasting the markup manually.  

Currently with `injectScripts` custom js is added at the end of the HTML proxied from the CMS. With proposed `injectStyles` I imagine that custom css bundle is added on the fly at the end of the <head>. Alternatively  `injectScripts` could inject both css and js parts at once - but this might be confusing given the name of the function.

Thanks for your help, cheers :)

**Comment by p-m-j** [comment]
Have you checked out the example project in the repo here?

basically you want your styles coming from javascript until you are ready to create a build for deployment, this way changes to css/sass etc can get pushed to the browser via hot module reloading.

**Comment by p-m-j** [comment]
It would absolutely be possible to use a css extract plug-in and append references to the markup, however this would be detrimental to dev experience.

It took me a while to buy into this concept when I first started using webpack after gulp but I am 100% sold now.

**Comment by bartosz-wesolowski-wttech** [comment]
I have checked the example and it seems that this issue can be closed :) Thanks for your help 👍
